### ISSUE TITLE
address as parameter

### ISSUE THREAD

**Issue by mm28ajos** [rnuske/komaletter#3]
Hey,

I was wondering whether there is a way to add the address and return-address as parameters to the file. I am having trouble to add the linebreaks via parameters between the street, city and country. See the example below.

Best

Markus  
```
---
return-address: 
  - Musterstr. 12
  - 34567 Musterstadt
signature-before: 5\baselineskip
lco: DIN
lang: de
opening: Hey
closing: Best regards
params: 
    set_address: street\ncity\ncountry

subject: Test Letter
signature: signature here
address:  "`r params$set_address`"

output: komaletter::komaletter
---
test letter.
```

**Comment by rnuske** [comment]
It rather seems to be an rmarkdown Parameterized Reports question. komaletter expects the `address` to be a YAML collection just as the `return-address`.

I tried to get at it via checking the intermediate .md file with `rmarkdown::render('test_letter.Rmd', clean=FALSE)`.
<details><summary>test_letter.knit.md:</summary>

```
---
return-address: 
  - Musterstr. 12
  - 34567 Musterstadt
signature-before: 5\baselineskip
lco: DIN
lang: de
opening: Hey
closing: Best regards
params: 
  set_address: street\ncity\ncountry

subject: Test Letter
signature: signature here
address:  "street\ncity\ncountry"

output: komaletter::komaletter
---
  test letter.
```
 
</details>  </br>



I played with `set_address`. Enclosing it in quotation marks leads to evaluated `\n`. But not to a valid YAML collection. 
<details><summary>test_letter.knit.md:</summary>

```
---
return-address: 
  - Musterstr. 12
  - 34567 Musterstadt
signature-before: 5\baselineskip
lco: DIN
lang: de
opening: Hey
closing: Best regards
params: 
  set_address: "street\ncity\ncountry"

subject: Test Letter
signature: signature here
address:  "street
city
country"

output: komaletter::komaletter
---
  test letter.
```
</details> </br> </br>


The closest I got was
```
params: 
  set_address: "\n  -street\n  -city\n  -country"
```
resulting in 
```
---
return-address: 
  - Musterstr. 12
  - 34567 Musterstadt
signature-before: 5\baselineskip
lco: DIN
lang: de
opening: Hey
closing: Best regards
params: 
  set_address: "\n  -street\n  -city\n  -country"

subject: Test Letter
signature: signature here
address:  "
  -street
  -city
  -country"

output: komaletter::komaletter
---
  test letter.
```
which still doesn't work because of the quotation marks.

**Comment by mm28ajos** [comment]
thank you a lot! Works like a charm!

**Comment by rnuske** [comment]
@mm28ajos I would appreciate if you could have a look at the new vignette `parameterized_letter.Rmd`. Does the vignette make sense to you? I welcome any comments or a pull request.

**Comment by mm28ajos** [comment]
Very detailed and helpful document!
On thing which I did in addition was splitting the fields into several parameters to have only atomic parameters since this saves the hassel to builde the correct strings at the calling script and avoids errors. Maybe you want to include that in the example:
```
---
author: Max Muster
params:
  recipient_surname: "John"
  recipient_name: "Doe"
  address_city: "Anytown"
  address_postalcode: "4321"
  address_country: ""
  address_street: "street"
  address_streetnumber: "1"
  returnaddress_street: "Musterstr."
  returnaddress_streetnumber: "12"
  returnaddress_postalcode: "34567"
  returnaddress_city: "Musterstadt"
  returnaddress_country: ""
  gift: candlestick

output: komaletter::komaletter
---
---
address: `r paste0('[', params$recipient_surname, ' ', params$recipient_name, ',', params$address_street, ' ', params$address_streetnumber, ',', params$address_postalcode, ' ', params$address_city, ',', params$address_country,']')`
return-address: `r paste0('[', params$returnaddress_street, ' ', params$returnaddress_streetnumber, ',', params$returnaddress_postalcode, ' ', params$returnaddress_city, ',', params$returnaddress_country,']')`

opening: `r paste0('Dear ', params$recipient_surname, ',')`
closing: "Yours truly,"
---

thank you very much for the beautiful `r params$gift`. It was a pleasure to have you.
```
And the calling example:
```
 recipients <- data.frame(recipient_surname=c("Megan", "Bob"),
                         recipient_name=c("Smith", "Pitts"),
                         address_city=c("Green Bay Indiana", "Fort Dodge GA"),
                         address_postalcode=c("19759", "20783"),
                         address_street=c("Tincidunt Ave", "Aliquet St"),
                         address_streetnumber=c("4156", "5543"),
                         gift=c("candlestick", "flowers"),
                         stringsAsFactors=FALSE)

for(i in 1:nrow(recipients)){
  rmarkdown::render("rmdtest.Rmd", 
                    params=list(recipient_surname=recipients[i, "recipient_surname"], 
                                recipient_name=recipients[i, "recipient_name"], 
                                address_city=recipients[i, "address_city"],
                                address_postalcode=recipients[i, "address_postalcode"], 
                                address_street=recipients[i, "address_street"], 
                                address_streetnumber=recipients[i, "address_streetnumber"], 
                                returnaddress_street="Musterstr.", 
                                returnaddress_streetnumber="12", 
                                returnaddress_postalcode="9088",
                                returnaddress_city="Musterstadt"),
                    output_file=paste0("letter_", recipients[i, 'recipient_surname'], ".pdf"))
}
```
